site_name: GenStudio
site_url: https://studio.gen.dev
repo_url: https://github.com/probcomp/genstudio
repo_name: probcomp/genstudio
edit_uri: tree/docs/docs/
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil-box
    download: material/download
  palette:
    primary: white
    accent: custom
  font:
    text: Crimson Pro
  features:
    # - navigation.tracking
    - navigation.indexes
    - toc.integrate
    - content.action.edit
  logo: false
nav:
  - Home: index.md
  - Getting Started: getting-started.py
  - Interactivity & Animation:
    - Sliders: interactivity/sliders.py
    - Re-rendering a plot: interactivity/reset.py
    - Animating through Frames: interactivity/frames.py
    - Browser events: interactivity/events.py
    - Refs: interactivity/refs.py
    - Tailing data: interactivity/tail.py
  - API Docs: api/plot.md
  - Learn More:
    - Working with Color: working-with-color.py
    - HTML with Hiccup: html-hiccup.py
    - Python Event Loops: python-event-loop.py
    - Compare with Observable Plot: comparison-with-observable.py
  - Examples:
      - Ellipse Mark: examples/ellipse-mark.py
      - Histogram Mark: examples/histogram-mark.py
      - Image Mark: examples/image-mark.py
      - Timelines with barX: examples/barx-timeline.py
      - Highlighting Code: examples/bylight.py
  - Changelog: CHANGELOG.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
plugins:
  - search
  - genstudio.docs.plugin:
      modules:
        - module: genstudio.plot
          output: api/plot.md
  - mkdocs-jupyter:
      include: ["*.py"]
      execute: true
      allow_errors: false
      kernel_name: genstudio
      include_requirejs: true
      include_source: True
      remove_tag_config:
        remove_cell_tags:
          - hide
        remove_input_tags:
          - hide_source
        remove_all_outputs_tags:
          - hide_output
extra_css:
  - stylesheets/custom.css
  - https://unpkg.com/bylight/styles/bylight.css
extra_javascript:
  - https://unpkg.com/bylight/dist/index.global.js
  - js/scroll-fix.js
  - js/bylight.js
  - js/command-k.js
hooks:
  - src/genstudio/scripts/css_modifier.py
