site_name: GenStudio
site_url: https://studio.gen.dev
repo_url: https://github.com/probcomp/genstudio
repo_name: probcomp/genstudio
edit_uri: tree/docs/docs/
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil-box
    download: material/download
  palette:
    primary: white
    accent: custom
  font:
    text: Crimson Pro
  features:
    - navigation.tracking
    - navigation.indexes
    - toc.integrate
    - content.action.edit
  logo: false
nav:
  - Home: index.md
  - Getting Started: getting-started.py
  - Animation & Interactivity: animate-interactive.py
  - HTML with Hiccup: html-hiccup.py
  - Python Event Loops: python-event-loop.py
  - Compare with Observable Plot: comparison-with-observable.py
  - More Examples:
      - Additional Marks: additions-to-observable.py
      - Timelines with barX: example-timelines.py
      - Synchronized Highlights: synchronized-highlights.py
  - Changelog: CHANGELOG.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
plugins:
  - search
  - mkdocs-jupyter:
      include: ["*.py"]
      execute: true
      kernel_name: genstudio
      include_requirejs: true
      include_source: True
      remove_tag_config:
        remove_cell_tags:
          - hide
        remove_input_tags:
          - hide_source
        remove_all_outputs_tags:
          - hide_output
extra_css:
  - stylesheets/custom.css
  - https://unpkg.com/bylight/styles/bylight.css
extra_javascript:
  - https://unpkg.com/bylight/dist/index.global.js
  - js/scroll-fix.js
  - js/bylight.js
  - https://cdn.twind.style
hooks:
  - src/genstudio/scripts/css_modifier.py
