site_name: GenStudio
site_url: https://studio.gen.dev
repo_url: https://github.com/probcomp/genstudio
repo_name: probcomp/genstudio
edit_uri: tree/docs/docs/
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil-box
    download: material/download
  palette:
    primary: black
    accent: blue
  font:
    text: Georgia
  features:
    - navigation.tracking
    - navigation.indexes
    - toc.integrate
    - content.action.edit
  logo: false
nav:
  - Home: index.py
  - User Guide:
      - The Basics: user-guide/basics.py
      - Animation & Interactivity: user-guide/animate-interactive.py
      - HTML with Hiccup: user-guide/html-hiccup.py
      - Python Event Loops: user-guide/python-event-loop.py
      - Compare with Observable Plot: user-guide/comparison-with-observable.py
      - Additional Marks: user-guide/additions-to-observable.py
  - More Examples:
      - Timelines with barX: examples/timelines.py
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - mkdocs-jupyter:
      include: ["*.py"]
      execute: true
      kernel_name: genstudio
      # no_input: True
      include_requirejs: true
      include_source: True
      remove_tag_config:
        remove_cell_tags:
          - hide
        remove_input_tags:
          - hide_source
        remove_all_outputs_tags:
          - hide_output
extra_css:
  - stylesheets/custom.css
extra_javascript:
  - js/uplight.js
  - js/scroll-fix.js
# poetry run ipython kernel install --user --name=genstudio

hooks:
  - src/genstudio/scripts/css_modifier.py
