site_name: GenStudio
site_url: https://studio.gen.dev
repo_url: https://github.com/probcomp/genstudio
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - toc.integrate
nav:
  - Home: index.py
  - User Guide: user-guide.py
  - More Examples:
    - Python Event Loop: examples/event-loop.py
plugins:
  - search
  - mkdocs-jupyter:
      include: ["*.py"]
      execute: true
      kernel_name: genstudio
      # no_input: True
      include_requirejs: true
      include_source: True
      remove_tag_config:
        remove_cell_tags:
          - hide
        remove_input_tags:
          - hide_source
        remove_all_outputs_tags:
          - hide_output
extra_css:
  - stylesheets/custom.css
extra_javascript:
  - uplight.js
# poetry run ipython kernel install --user --name=genstudio
