name: Docs Website

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  actions: read
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Debug Info
      run: |
        echo "Current branch: ${{ github.ref }}"
        echo "Event name: ${{ github.event_name }}"
        echo "Commit SHA: ${{ github.sha }}"

    - name: Yarn deps
      run: yarn install --frozen-lockfile --production=false

    - name: JavaScript bundle
      run: yarn build

    - name: Python install
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Poetry Install
      uses: snok/install-poetry@v1
      with:
        version: 1.8.3
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: "${{ secrets.ARTIFACT_REGISTRY_KEY }}"
    - name: Deploy key config
      run: |
        poetry self add keyrings.google-artifactregistry-auth
        poetry config repositories.gcp https://us-west1-python.pkg.dev/probcomp-caliban/probcomp/
    - name: Python deps (via poetry)
      run: poetry install
    - name: Kernel install
      run: poetry run python -m ipykernel install --user --name genstudio
    - name: mkdocs build
      run: poetry run mkdocs build
    - name: Copy llms.py to site
      run: cp docs/llms.py ./site/
    - name: Artifact upload
      uses: actions/upload-artifact@v4
      with:
        name: website
        path: ./site

  publish:
    if: github.ref == 'refs/heads/main'
    permissions:
        contents: read
        id-token: write
    needs: prepare
    uses: probcomp/gen-website-private/.github/workflows/publish_private_website.yml@main
    with:
      artifact: website
      subdomain: studio
