name: Docs Website

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Yarn deps
      run: yarn install --frozen-lockfile --production=false

    - name: JavaScript bundle
      run: yarn build

    - name: Python install
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.5
    - name: Poetry Install
      uses: snok/install-poetry@v1
      with:
        version: 1.8.3
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: "${{ secrets.ARTIFACT_REGISTRY_KEY }}"
    - name: Deploy key config
      run: |
        poetry self add keyrings.google-artifactregistry-auth
        poetry config repositories.gcp https://us-west1-python.pkg.dev/probcomp-caliban/probcomp/
    - name: Python deps (via poetry)
      run: poetry install
    - name: Kernel install
      run: poetry run python -m ipykernel install --user --name genstudio
    - name: mkdocs build
      run: poetry run mkdocs build
    - name: Copy llms.py to site
      run: cp docs/llms.py ./site/
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
